로그인 및 회원가입 ui + 기능 구현
MeetUpEat/Zipbab pull request #10
Opened 2024-05-31 09:07 UTC by kory0115

close #5 
## (필수) 기능 구현 목록

- 로그인 ui구현
- 회원가입 ui구현
- 로그인 및 회원가입 기능구

## (필수) 스크린샷

https://github.com/MeetUpEat/Rice/assets/124674637/964fce15-c9ee-4daf-a477-cd1801214cef

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

- 구현한 코드가 처음 설계했을떄 의도와 부합한지 봐주셨으면 좋겠습니다.
- 전체적인 ui 나 코드 구성 부분

## 참고사항

- navi fragment설정에서 처음시작값을 loginfragment로 설정해주시면 됩니다.

2024-05-31 10:38 UTC, DoTheBestMayB requested changes

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/MainActivity.kt
> +import com.bestapp.rice.ui.login.LoginFragment
사용하지 않는 import 문은 지워주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            }
아이디 저장 여부는 로그인 성공 시에 이루어지기 때문에 누를 떄마다 dataStore에 있는 값을 변경하기 보다는 로그인에 성공했을 때 처리하는 게 좋겠습니다.
또한 dataStore가 아닌 AppSettingRepository를 통해 DataStore에 간접적으로 요청하시면 됩니다.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +    private fun initViews() {
initViews보다는 Listener 처리와 관련된 이름으로 변경하는 것이 좋겠습니다.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            }
typeChange 값 변경을 한 줄로 줄여보면 어떨까요?

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +        object : TextWatcher {
Push 하기 전에 코드 정렬을 해주시면 가독성이 더 좋아집니다.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +        <androidx.appcompat.widget.AppCompatImageButton
AppCompat이 아닌 Material 테마에 속한 View를 사용해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +        <androidx.appcompat.widget.AppCompatButton
AppCompat이 아닌 Material에 속한 View를 사용해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +            android:textSize="15sp"
미리 정의한 textStyle을 이용해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="16dp"
1. 미리 정의한 dimen margin 값을 이용해주세요.
2. 좌우 여백은 20dp로 변경됐습니다.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +            android:background="@drawable/background_button_disable"
material button에서 backgroundTint로 색상이 변경되지 않아 Appcompat으로 바꾼 후 Drawable을 이용하신 거로 생각되는데,
Theme style을 이용하면 Material Button의 색상을 변경할 수 있습니다.

저희 앱 색상을 이용한 Button Style은 제가 미리 만들어뒀으니, 제 코드가 merge 되면, 해당 style을 이용하도록 수정해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +        binding.passwordEditText.addTextChangedListener( @SuppressLint("RestrictedApi")
이 애노테이션을 설정하신 이유는 무엇인가요?

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:visibility="gone"
UI가 어떻게 구성되어있는지 Preview에서 보기 위해, tools:visibility를 설정해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:id="@+id/remember_text"
1. 네이밍 컨벤션을 지켜주세요.
2. 해당 View는 약관과 관련된 안내 문구로 보이는데, 네이밍을 역할에 어울리게 지어주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            ForegroundColorSpan(Color.parseColor("#009EE2")),
색상은 colors.xml에 정의해서 사용해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            11,
하드 코딩된 값은 이것이 무엇을 하는지 알기 어려워요.
관련 키워드: magic number

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +        Linkify.addLinks(binding.rememberText, pattern, "", null, mTransform)
mTransform은 어떤 역할을 하나요? 또한 왜 빈 값으로 두신지 궁금합니다.
pattern은 regex를 입력하라고 되어 있는데, 이용약관을 입력하신 이유는 무엇인가요?

addLinks 함수 호출시 scheme과 matchFilter를 빈 값으로 두신 이유는 무엇인가요?

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +    @SuppressLint("SetTextI18n")
SuppressLint 애노테이션을 무조건 사용하지 마시고, IDE가 알려주는 문구를 읽고 수정해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            //firestore 에 값저장
firestore에 값을 저장해야 한다면 viewModel을 생성한 후, viewModel에서 관련 작업을 처리하는 repository 함수를 호출해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +                binding.dateEditText.setText("${i}/${i2 + 1}/${i3}")
String format을 사용해주세요.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            val picker = context?.let { it1 -> DatePickerDialog(it1, listener, year, month, day) }
context는 왜 nullable일까요? requireContext는 왜 있는 걸까요?

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +                if(binding.nameEditText.length() > 2) {
Magic Number는 지양해야 하며, 중요한 숫자 값은 별도로 관리해야 합니다.

2024-05-31 10:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +                    binding.compareResultText.text = "비밀 번호가 일치 합니다."
1. if 조건 문이 너무 깁니다.
2. 문자열은 strings로 추출한 후 사용해주세요.

2024-05-31 11:08 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +        binding.passwordEditText.addTextChangedListener( @SuppressLint("RestrictedApi")
addTextChangedListener 에서 override되는것중에 필요한1개를 override할려고 TextWatcherAdapter를 사용했는데 그것때문에 설정한것같습니다.

2024-05-31 11:10 UTC, kory0115 commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:id="@+id/remember_text"
수정했습니다.

2024-05-31 11:16 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +        Linkify.addLinks(binding.rememberText, pattern, "", null, mTransform)
scheme는 나중에 약관페이지를 만들었을경우 연결할예정입니다.
mTransform은 scheme마지막부분에 덧붙여지는 기능으로 알고있습니다.
이용약관이 들어간 부분을 문자열에서 찾기위해서 적었습니다.

2024-05-31 11:27 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:id="@+id/remember_text"
수정하신 커밋 링크 복사해서 코멘트와 함께 첨부해주시면 확인 하기에 용이할 것 같습니다.

2024-05-31 11:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +                    binding.compareResultText.text = "비밀 번호가 일치 합니다."
coo

[fix: re-request](https://github.com/MeetUpEat/Rice/pull/10/commits/7e95a90c2baf2335b0214998fc4871cd35ac2083)

2024-05-31 11:59 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +        <androidx.appcompat.widget.AppCompatImageButton
[fix: 정의된 font 값으로 변경](https://github.com/MeetUpEat/Rice/pull/10/commits/59975b8d11bd6ca103aeead1f4508c4c92a53cff)

2024-05-31 12:00 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +            android:textSize="15sp"
[fix: 정의된 font 값으로 변경](https://github.com/MeetUpEat/Rice/pull/10/commits/59975b8d11bd6ca103aeead1f4508c4c92a53cff)

2024-05-31 12:00 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +            android:layout_marginTop="16dp"
[fix: 정의된 font 값으로 변경](https://github.com/MeetUpEat/Rice/pull/10/commits/59975b8d11bd6ca103aeead1f4508c4c92a53cff)

2024-05-31 12:00 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +            android:background="@drawable/background_button_disable"
[fix: 정의된 font 값으로 변경](https://github.com/MeetUpEat/Rice/pull/10/commits/59975b8d11bd6ca103aeead1f4508c4c92a53cff)

2024-06-03 10:55 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            val picker = context?.let { it1 -> DatePickerDialog(it1, listener, year, month, day) }
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:55 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            //firestore 에 값저장
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:55 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            ForegroundColorSpan(Color.parseColor("#009EE2")),
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:55 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +            android:textSize="15sp"
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:56 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
> +        <androidx.appcompat.widget.AppCompatButton
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:56 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +        object : TextWatcher {
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 10:56 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +    private fun initViews() {
[fix: 전반적인 코드 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/7774029bacab5ef9838d6b5c479066933d5413d4)

2024-06-03 13:03 UTC, rlaxodud214 requested changes
[필수] xml 파일에서 컴포넌트의 id 값이 논의된 컨벤션 규칙에 적합하지 않은 것 같습니다! 
수정해주시면 좋을 것 같아요

2024-06-03 13:03 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            }
이런 주석은 TODO로 처리하면 추후에 좀 더 관리가 편해질 것 같습니다!

2024-06-03 13:03 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +                        binding.loginButton.setBackgroundResource(R.drawable.background_button)
이 코드가 addTextChangedListener에서도 반복되는데 별도의 함수로 빼는 건 어떨까요?

2024-06-03 14:26 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +                        binding.loginButton.setBackgroundResource(R.drawable.background_button)
[fix: 추가수정](https://github.com/MeetUpEat/Rice/pull/10/commits/e8a615ca544536fc378dd09fe8c2241d569daf95)

2024-06-03 14:26 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            }
[fix: 추가수정](https://github.com/MeetUpEat/Rice/pull/10/commits/e8a615ca544536fc378dd09fe8c2241d569daf95)

2024-06-05 03:03 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셨습니다.

2024-06-05 03:03 UTC, yoonchanchoi commented on app/src/main/res/values/strings.xml
> +    <string name="nick_name">닉네임</string>
어느 화면에서 사용하는 것인지 해당 name앞에 Framgent의 이름을 붙여주시면 더 좋을 것 같아용~~^^😁
예를 들어 LoginFragment에서 사용하는 거면 login_nick_name처럼용 ㅎㅎ

2024-06-05 07:55 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_login.xml
>              android:id="@+id/remember_text"
사전에 논의된 컴포넌트 id 컨벤션 예시대로 고치면 아래와 같이 돼야합니다!
팀 노션의 5.컨벤션을 참고해주시면 좋을 것 같아요!

> 뷰 이름 : 속성_용도(사용방법) ⇒ Ex) <TextView> id 값 : tv_title
tv_remember_text

2024-06-05 09:28 UTC, DoTheBestMayB approved these changes

2024-06-05 09:28 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            findNavController().popBackStack()
현재 dev에 merge 된 코드로 해당 기능을 구현할 수 있습니다.

2024-06-05 09:28 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +}
ViewModel이 비어 있습니다! 아직 필요하지 않으면, 나중에 필요한 시점에 만드는 것이 좋겠습니다.

2024-06-05 09:28 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpViewModel.kt
> +}
현재 dev에 해당 repository 구현체를 이용할 수 있습니다.

2024-06-05 09:28 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_login.xml
> +            android:background="@drawable/background_button_disable"
제가 이전 리뷰에서 언급했던 Style은 styles.xml에 SquareButton로 정의되어 있습니다.

2024-06-05 10:36 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginFragment.kt
> +            findNavController().popBackStack()
머지후 새로 branch새로파서 적용하겠습니다.

2024-06-05 11:33 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
>              android:id="@+id/remember_text"
[fix: 컨벤션에 맞게 수정](https://github.com/MeetUpEat/Rice/pull/10/commits/273416afc1a7739ca72ba9ef0ffa9354de76aab2)

2024-06-05 11:43 UTC, rlaxodud214 approved these changes
컴포넌트 약어 부분 컨벤션에 대해서는 에너지가 남아 있다면 수정 후, merge 해주시면 되겠습니다!! 아니면 이후에 하셔도 됩니다! 고생하셨어요!!!

2024-06-05 12:15 UTC, merged