Feat/#4 홈 화면 UI와 기본 필요한 동작 구현
MeetUpEat/Zipbab pull request #12
Opened 2024-05-31 20:00 UTC by yoonchanchoi

## (필수) 기능 구현 목록

- 홈 화면 UI와 기본 필요한 동작 구현

## (필수) 스크린샷

<img src="https://github.com/MeetUpEat/Rice/assets/74814647/298b927c-7736-4d81-939c-afad5908277a" width="200" height="400">
<img src="https://github.com/MeetUpEat/Rice/assets/74814647/51b33906-20b0-4ad1-94e9-70f85c9e1289" width="200" height="400">

## (선택) Issue 

- 한 줄 요약: 홈 화면 기본 동작 구현
- 세부 내용: 홈 화면에 들어가는 아이템은 더미 데이터로 만들었고 추가로 해당 이미지는 일단 기본 이미지를 기본으로 정해서 넣었습니다. 각각의 화면의 버튼 클릭 시 해당 다음 화면으로 이동합니다.

## 참고사항
- 화면 이동 기능 중에 빠진 부분은 TODO로 남겼습니다. 추가로 아직 디자인 수정으로 인해 추후에 layout이 수정 될 수 있습니다.
- 아래는 더미데이터 코드입니다.

```kotlin
package com.bestapp.rice.data.repository

import com.bestapp.rice.data.model.remote.Meeting
import com.bestapp.rice.data.model.remote.PlaceLocation

class FakeMeetingRepositoryImp: MeetingRepository {
    override suspend fun getMeeting(meetingDocumentID: String): List<Meeting> {
        TODO("Not yet implemented")
    }

    override suspend fun getSearch(query: String): List<Meeting> {
        TODO("Not yet implemented")
    }

    override suspend fun getFoodMeeting(mainMenu: String): List<Meeting> {
        TODO("Not yet implemented")
    }

    override suspend fun getCostMeeting(costType: Int): List<Meeting> {
        TODO("Not yet implemented")
    }

    override suspend fun createMeeting(mainMenu: String): List<Meeting> {
        TODO("Not yet implemented")
    }

    override suspend fun updateAttendanceCheckMeeting(meetingDocumentID: String) {
        TODO("Not yet implemented")
    }

    override suspend fun endMeeting(meetingDocumentID: String) {
        TODO("Not yet implemented")
    }

    override suspend fun addPendingMember(meetingDocumentID: String) {
        TODO("Not yet implemented")
    }

    override suspend fun approveMember(meetingDocumentID: String) {
        TODO("Not yet implemented")
    }

    override suspend fun rejectMember(meetingDocumentID: String) {
        TODO("Not yet implemented")
    }

    override suspend fun getMeetingByUserDocumentID(): List<Meeting> {
        return listOf(
            Meeting(
                meetingDocumentID = "aperiri",
                title = "제목1",
                titleImage = "finibus",
                placeLocation = PlaceLocation(
                    locationAddress = "mnesarchum",
                    locationLat = "1",
                    locationLong = "0"
                ),
                time = "시간1",
                recruits = 6082,
                description = "detracto",
                mainMenu = "contentiones",
                costValueByPerson = 8126,
                costTypeByPerson = 5915,
                host = "persecuti",
                members = emptyList(),
                pendingMembers = emptyList(),
                attendanceCheck = emptyList(),
                activation = true
            ),
            Meeting(
                meetingDocumentID = "aperiri",
                title = "제목2",
                titleImage = "finibus",
                placeLocation = PlaceLocation(
                    locationAddress = "mnesarchum",
                    locationLat = "1",
                    locationLong = "0"
                ),
                time = "시간2",
                recruits = 6082,
                description = "detracto",
                mainMenu = "contentiones",
                costValueByPerson = 8126,
                costTypeByPerson = 5915,
                host = "persecuti",
                members = emptyList(),
                pendingMembers = emptyList(),
                attendanceCheck = emptyList(),
                activation = true
            ),
            Meeting(
                meetingDocumentID = "aperiri",
                title = "제목3",
                titleImage = "finibus",
                placeLocation = PlaceLocation(
                    locationAddress = "mnesarchum",
                    locationLat = "1",
                    locationLong = "0"
                ),
                time = "시간3",
                recruits = 6082,
                description = "detracto",
                mainMenu = "contentiones",
                costValueByPerson = 8126,
                costTypeByPerson = 5915,
                host = "persecuti",
                members = emptyList(),
                pendingMembers = emptyList(),
                attendanceCheck = emptyList(),
                activation = true
            ),
            Meeting(
                meetingDocumentID = "aperiri",
                title = "제목4",
                titleImage = "finibus",
                placeLocation = PlaceLocation(
                    locationAddress = "mnesarchum",
                    locationLat = "1",
                    locationLong = "0"
                ),
                time = "시간4",
                recruits = 6082,
                description = "detracto",
                mainMenu = "contentiones",
                costValueByPerson = 8126,
                costTypeByPerson = 5915,
                host = "persecuti",
                members = emptyList(),
                pendingMembers = emptyList(),
                attendanceCheck = emptyList(),
                activation = true
            )
        )
    }
}
````

```kotlin
package com.bestapp.rice.data.repository

import com.bestapp.rice.data.model.remote.PlaceLocation
import com.bestapp.rice.data.model.remote.User

class FakeAppSettingRepositoryImpl: AppSettingRepository {
    override suspend fun getPrivacyInfo(): String {
        TODO("Not yet implemented")
    }

    override suspend fun getUserInfo(): User {
        return User(
            userDocumentID = "test",
            nickName = "",
            id = "",
            pw = "",
            profileImage = "",
            temperature = 0.0,
            meetingCount = 0,
            posts = emptyList(),
            placeLocation = PlaceLocation(
                locationAddress="",
                locationLat = "",
                locationLong= ""
            )
        )
    }
}
```

```kotlin
package com.bestapp.rice.data.repository

import com.bestapp.rice.data.R
import com.bestapp.rice.data.model.remote.Filter

class FakeCategoryRepositoryImpl : CategoryRepository {
    override suspend fun getFoodCategory(): List<Filter> {
        return listOf(
            Filter.Food(
                "R.drawable.img_test",
                "파스타"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "찌개"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "백반"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "구이"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "떡볶이"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "샌드위치"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "베이커리"
            ),
            Filter.Food(
                "R.drawable.img_test",
                "전"
            )
        )
    }

    override suspend fun getCostCategory(): List<Filter> {
        return listOf(
            Filter.Cost(
                "R.drawable.img_test",
                "~3만원",
                1
            ),
            Filter.Cost(
                "R.drawable.img_test",
                "3~5만원",
                2
            ),
            Filter.Cost(
                "R.drawable.img_test",
                "5~10만원",
                1
            ),
            Filter.Cost(
                "R.drawable.img_test",
                "10만원~",
                1
            )
        )
    }

}
```

2024-06-01 06:48 UTC, kory0115 approved these changes

2024-06-01 16:38 UTC, DoTheBestMayB requested changes

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModelFactory.kt
> +
제가 Fake 객체 사용방법을 제안 드렸는데, PR 올릴 때가 애매하네요.

XxxRepositoryImpl 네이밍으로, 함수 body를 TODO로만 구성된 클래스를 만들고, 여기에 작성해주신 클래스들을 변경해주세요.

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +        //findNavController().navigate(action)
필요한 Action이 있다면 NavGraph에 추가한 후 사용해주세요!

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +            setPaddingValues(topDp = 8, bottomDp = 8, startDp = 16, endDp = 16)
dimens에 있는 패딩 값을 불러와서 사용하면 관리하기에 더 용이할 것 같아요

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModel.kt
> +                if (it) {
it 대신 user가 로그인 된 상태인지를 나타내는 변수로 지정하면 더 명확해질 것 같아요

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/GoNavigate.kt
> +    GONO, GOLOGIN, GOCREATMEET
단어 사이에 언더바를 넣어주세요

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_home.xml
> +                android:layout_marginEnd="20dp"
dimen에 정의된 Margin 값을 사용해주세요.

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +        viewModel.getMeetingByUserDocumentID()
setupData 함수에 넣기에 적절해 보이네요

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostDiffUtil.kt
> +}
1. 각 함수의 구현이 잘못되어 있습니다.
RecyclerView가 새로운 아이템이 들어왔을 때 어떤 순서로 비교하는지 찾아보고 수정해주세요!
2. Kotlin에서 ==와 ===의 차이는 무엇일까요? 또한 자바의 ==, ===와 어떤 차이가 있을까요?

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
ViewHolder를 여러 Adapter에서 사용하지 않는다면, 보통은 Adapter의 중첩 클래스로 선언합니다!

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
> +        binding.iv.load(R.drawable.ic_launcher_background)
1. costUiState의 icon을 로딩하도록 수정해주세요!
2. costUiState의 icon 주솟값을 ImageUiState로 관리하면 더 좋을 것 같아요(디스코드 협의사항에 관련 내용 작성했습니다!)
3. 여기 뿐만 아니라 다른 ViewHolder에도 동일하게 수정해주세요!

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/FoodMenuViewHolder.kt
> +import android.util.Log
IDE 코드 정리 기능을 이용하면 사용하지 않는 import문과 코드를 정렬해줍니다!

사용하지 않는 import 문 삭제: Ctrl + Alt + O
코드 정렬 : Ctrl + Alt + L

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_home.xml
> +            </androidx.constraintlayout.widget.ConstraintLayout>
ScrollView 내에서 RecyclerView 아이템이 모두 표시되지 않도록 하기 위해 ConstraintLayout 하위에 두신거죠? 아이디어 👍

구현하실 때 참고하신 글이 있다면 알 수 있을까요? 성능적인 부분이나 구현 관련 설명을 보고 싶네요!

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_home.xml
> +        app:srcCompat="@drawable/baseline_add_24" />
플로팅 버튼에 적용한 속성을 style로 빼보면 좋겠습니다!

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/res/values/colors.xml
> +    <color name="clr_C4E4F1">#C4E4F1</color>
색상 값보다는 사용되는 장소나 목적을 적어주시면 재활용하기 좋겠습니다.

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/res/layout/item_cost.xml
> +        android:text="5~10만원"
프리뷰를 위한 값은 tools로 지정해주세요.

2024-06-01 16:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/GoNavigate.kt
> +enum class GoNavigate {
클래스 이름을 명사로 변경하면 어떤 클래스인지 알아보기 더 좋겠습니다.

2024-06-01 16:55 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +    }
메모리 누수 방지를 위해 adapter도 onDestroyView에서 null 처리를 하는 게 어떨까요?

https://write.agrevolution.in/memory-leaks-in-android-apps-45a27c6ac35d

2024-06-01 17:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +    }
@rlaxodud214 연락처 앱 구현 당시 ViewPagerAdapter 사용할 때 onDetach가 자동으로 호출되지 않아 메모리 누수가 발생하는 것을 확인했었습니다.

그러면 일반 Adapter도 메모리 누수가 발생하는지 확인해보니, null처리를 하지 않아도 GC에 의해 회수 됐습니다.

그런데 엄청 빠르게 화면을 계속 회전하면 간혹 카나리에서 메모리 누수가 발생했다고 나온적이 있습니다.

이거 관련해서 글 작성하다가, 카나리 때문인지, 정말 수동으로 null처리를 해야 하는지 확실하지 않아서 미뤄뒀는데, 오늘 오후에 확인해보고 관련 내용 공유드릴게요.

2024-06-01 17:40 UTC, rlaxodud214 approved these changes

2024-06-01 23:02 UTC, kory0115 approved these changes

2024-06-03 02:09 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +    }
ListAdapter와 Viewpager 모두 별도의 null 처리를 하지 않아도 메모리 회수가 잘 되네요.
전에 분명히 메모리 누수를 경험했는데, 다시 재현이 안 됩니다..

테스트 해본 코드 : https://github.com/DoTheBestMayB/AdapterStudy
ViewPager2 메모리 누수 관련 issueTracker : https://issuetracker.google.com/issues/151212195

2024-06-03 13:30 UTC, rlaxodud214 approved these changes
고생하셨습니다!!

2024-06-03 13:30 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostDiffUtil.kt
> +}
아래 공식 문서를 참고하시면 좋을 것 같습니다!

https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil.ItemCallback#areItemsTheSame(T,T)

2024-06-03 13:30 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_home.xml
> +            <EditText
textAppearance 속성이 누락된 것 같습니다!

2024-06-03 15:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +    }
null 처리를 안 하면 메모리 누수 되는 것이 맞습니다!

2024-06-03 17:23 UTC, yoonchanchoi reviewed
한번 확인해주세요^^

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/GoNavigate.kt
> +enum class GoNavigate {
ba915760014b14610635bf59aacea7acf0e5ee75

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/GoNavigate.kt
> +    GONO, GOLOGIN, GOCREATMEET
255ca3473b1a61f70c54b2bbbbfc9b8ca31b418c

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +    }
bf7e5c758659295c998d91d160e026aab9b7b18b
👍

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +        //findNavController().navigate(action)
이 부부은 해당 한번 더 체크해 보고 추가할 게용 최대한 빠르게
일단 급하게 짜놓은 거라 ㅎㅎ

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModelFactory.kt
> +
어떤 식으로 말씀이신지 한번 예제를 보여주 실 수 있나용?

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
혹시 어떤 이유에서 인지 알 수 있을까용?😀

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_home.xml
> +            <EditText
a2c80bce5708a51e4697817bf3ec42ab2b73b5f1
👍

2024-06-03 17:23 UTC, yoonchanchoi commented on app/src/main/res/values/colors.xml
> +    <color name="clr_C4E4F1">#C4E4F1</color>
해당 부분 같이 결정해야 될 것 같아용😁
왜냐하면 원래는 디자이너가 있을 경우 해당 명칭을 정해주거나 색상 컬러 값을 이름으로 해주는 경우도 있어서요..그래서 일단 알기 쉽게 직관적으로 표현했습니다.
그리고 해당 부분이 대표 컬러가 정해지지 않은 부분도 있네요^^
사용 위치 자체는 layout의 stroke, soild에서 사용한 부분입니다.

2024-06-03 17:26 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModel.kt
> +                if (it) {
c3db32f8ef909415aed97820f53962b1c83b4ee6
👍

2024-06-03 17:28 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeFragment.kt
> +            setPaddingValues(topDp = 8, bottomDp = 8, startDp = 16, endDp = 16)
4336869c71a14ad4458c146771f96d12cc9f64a5
👍

2024-06-03 17:30 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_home.xml
> +        app:srcCompat="@drawable/baseline_add_24" />
```
    <style name="round" parent="ShapeAppearance.Material3.SmallComponent">
        <item name="cornerFamily">rounded</item>
        <item name="cornerSize">50dp</item>
    </style>
```

해당부분으로 style해서 Overlay를 한 것입니다..
혹시 어떤 식으로 말씀 이신지 예제를 보여주실 수 있을까용?

2024-06-03 17:30 UTC, yoonchanchoi commented on app/src/main/res/layout/item_cost.xml
> +        android:text="5~10만원"
9c203156a4fc57d2e417ca78228d67a440349448
👍

2024-06-04 01:54 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModelFactory.kt
> +
FakeAppSettingRepositoryImpl 클래스 대신 AppSettingRepositoryImpl 클래스를 사용하시면 됩니다!

2024-06-04 02:01 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/home/recyclerview/CostViewHolder.kt
공식 문서에도 nested class로 선언 되어 있고, 다른 곳에서 사용하지 않는다면, 사용하는 곳에서 관리하는 것이 맞다고 생각했습니다!

https://developer.android.com/develop/ui/views/layout/recyclerview#implement-adapter

2024-06-04 02:04 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_home.xml
> +        app:srcCompat="@drawable/baseline_add_24" />
```kotlin
    <style name="SquareButton">
        <item name="android:textColor">@color/main_color</item>
        <item name="backgroundTint">@color/main_color_transparent_20</item>
        <item name="shapeAppearanceOverlay">@style/SquareButtonRounded</item>
    </style>
```

2024-06-04 02:07 UTC, DoTheBestMayB approved these changes
수고하셨습니다👍

2024-06-05 02:57 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/home/HomeViewModelFactory.kt
> +
8e11c645ff5c8001ad1863a6065045d758e4c13c

2024-06-05 02:57 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_home.xml
> +        app:srcCompat="@drawable/baseline_add_24" />
c235cd468f0fbcbabddf33fd39b9b3d3181fd591

2024-06-05 09:15 UTC, merged