프로필 화면 구현
MeetUpEat/Zipbab pull request #14
Opened 2024-06-01 14:39 UTC by DoTheBestMayB

## 기능 구현 목록

- 프로필 화면 구현

## 스크린샷

다른 사람 프로필
<img src="https://github.com/MeetUpEat/Rice/assets/48354989/0335afa3-3056-4c22-ad86-c0c56570ff4e" width="300" height="600">

본인 프로필
<img src="https://github.com/MeetUpEat/Rice/assets/48354989/664285c3-7286-4542-bee3-4a636026c4e2" width="300" height="600">

<img src="https://github.com/MeetUpEat/Rice/assets/48354989/656bdc38-ee18-48d9-9614-4007287f2401" width="300" height="600">

## 참고사항

- 이미지를 String이 아닌 Image, ImageUiState 클래스로 관리하도록 변경함
- 버튼 등의 디자인이 기본으로 설정되어 있는 이유는 사용사 설정 페이지 구현 시 정의한 Style을 사용해야 하는데, 아직 머지되지 않아서임
- 테스트하기 위한 Fake 코드는 아래 파일을 다운받고 사진처럼 Apply Patch로 이 파일을 지정하면 됨
[fake.txt](https://github.com/user-attachments/files/15522192/fake.txt)

![image](https://github.com/MeetUpEat/Rice/assets/48354989/5a0c4219-ee8e-4fa4-aa37-b8ed74fa446f)

2024-06-01 23:16 UTC, kory0115 approved these changes

2024-06-02 09:30 UTC, kory0115 approved these changes

2024-06-05 03:15 UTC, yoonchanchoi approved these changes
구현하시느라 고새아하셧습니다.

2024-06-05 03:15 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            launch {
lanuch로 따로 분리해서 하면 
매번 viewLifecycleOwner.lifecycleScope.launch를 매번 사용 할 필요가 없군요.
혹시 차이가 있나용? 
차이가 없다면 해당 코드 처럼 보일러플레이트 코드를 줄일 수 있을 것 같네용 👍

2024-06-05 03:26 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            launch {
한 개의 observing launch block이 exception 등으로 cancel 되면 같은 부모 아래 있는 모는 자식들이 모두 취소된다는 점만 제외하면 기능은 동일합니다!

2024-06-05 05:02 UTC, rlaxodud214 requested changes
data class 부분 위주로 변경해주시면 좋을 것 같습니다!!

고생이 많으세요

2024-06-05 05:02 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +    private fun setTemperatureUI(userUiState: UserUiState) {
User에 대한 UI 세팅 코드로 보입니다! 메서드 이름을 바꿔보는 건 어떨까요?

2024-06-05 05:02 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
추후에 리팩토링 과정에서 해당 data class는 지워 주시는 게 맞을까요?

2024-06-05 05:02 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>              postUiStates = user.posts.map {
data class의 바디에는 convert를 위한 파라미터나 부 생성자를 제외하면, 들어가지 않는 것이 좋다고합니다.
특히 companion object는 피해야 할 1순위라고 합니다. (튜터님 피드백 내용)

createFrom 등의 메서드는 User.createFrom()의 확장함수로 변경하여 사용하는 것이 좋다고 합니다.

그 이유는 많이 설명해주셨지만, 
1. 기존에는 앞에 UserUiState만 붙이면, 모든 곳에서 함수 호출이 가능하지만, 확장함수로 수정하면 User 객체에 한해서만 호출할 수 있어 호출할 수 있는 범위에 제약을 둘 수 있어 더 명확하다고 합니다.

[nowInAndroid](https://github.dev/android/nowinandroid/blob/85129e4660f7a27c7081f4ac21169d19db89fbb6/core/model/src/main/kotlin/com/google/samples/apps/nowinandroid/core/model/data/UserNewsResource.kt)에서도 data class는 부 생성자를 제외하고 바디를 사용하지 않는 패턴이 보여집니다!

2024-06-05 05:02 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>  @Parcelize
UserUiState에 직렬화가 언제 필요한지 궁금합니다

2024-06-05 05:02 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +class ProfileFragment : BaseFragment<FragmentProfileBinding>(FragmentProfileBinding::inflate) {
전에 공통 binding 처리를 위한 BaseFragment 구현하셨는데 출처가 궁금합니다.

2024-06-05 07:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +    private fun setTemperatureUI(userUiState: UserUiState) {
[chore: 갱신된 사용자 정보에 따라 View를 갱신하는 함수 이름 수정](https://github.com/MeetUpEat/Rice/pull/14/commits/7ca9c7adcf5dbda962b5696b4abb594a443ef128)

2024-06-05 07:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
![image](https://github.com/MeetUpEat/Rice/assets/48354989/e6d2e8e1-5617-4325-8c11-1e2ddfcc0416)

url을 String으로 관리하는 것보다, data class로 wrapping 함으로써 이미지의 주솟값을 나타내는 것이 명확하다고 생각했는데, Image 클래스를 생성하면 수정해야 할 부분이 많아지나요?

2024-06-05 07:50 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
저는 개인적으로 파라미터의 이름 만으로도 충분히 이미지의 주솟값을 나타낼 수 있다고 생각됩니다!

Image class를 쓰는 건 관계 없지만, 코드 상으로 하나의 data class로 묶여있다는 게 
Image class 안에 uri 타입, 온라인 Link, Bitmap 타입 등 Image에 대한 여러 데이터를 하나의 class로 묶어서 관리하는 것 처럼 보여서 지우는 게 좋을 것 같다고 생각했습니다!

2024-06-05 07:53 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>              postUiStates = user.posts.map {
Empty 변수 같은 경우는 어떻게 처리해야 한다고 피드백 받으셨나요?

2024-06-05 08:00 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>              postUiStates = user.posts.map {
companion object 내부에 파라미터가 없는 메서드를 말씀하시는 게 맞을까요?

어떤 `Empty 변수`를 말씀하시는 것인지 제대로 이해하지 못했습니다.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            }
튜터 님 피드백
3개의 UiState를 별도로 emit 하지 말고 1개의 UiState로 emit 하는 것이 좋다.
관리도 더 편해진다.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
튜터 님 피드백

1. UiState를 다른 Fragment에 전달하기 위해 사용하는 것은 옳지 않다. 필요하다면 XxxUiState 클래스 자체를 전달하지 말고, 전달을 위한 별도의 클래스를 만들어서 사용해야 한다.
즉, UiState에 Parcelable 없애기
2. url 만을 위해 wrapping 하는 것은 불필요해 보인다.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>          val Empty = UserUiState(
튜터님 피드백

클래스가 아니기 때문에 대문자가 아닌 소문자로 바꾸기

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +class ProfileFragment : BaseFragment<FragmentProfileBinding>(FragmentProfileBinding::inflate) {
튜터 님 피드백

BaseFragment가 꼭 필요한지 생각해봐야 한다. 면접에서 왜 사용했냐고 물어봤을 때, 똑같은 코드가 반복 되서 사용했다, 그냥 편해서 썼다고 답변하면 안 좋은 인상을 줄 수 있다.
-> BaseFragment 걷어내는 방향으로 가는 것이 좋겠다.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +        val visibility = if (isVisible) View.VISIBLE else View.GONE
튜터 님 피드백

1. visibility를 if else로 처리하면, visible 체크가 누락되는 순간이 언젠가 올 것이다. if-else 로 하는 대신 scope function으로 변경하기
2. view의 visibility를 boolean으로 관리하지 않고, View의 isVisibile 확장 함수를 사용하는 것이 좋겠다.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +        }
튜터 님 피드백

1. 등록한 callback이 Fragment가 파괴되면 자동으로 끊어지는 지 내부코드 또는 디버깅으로 확인해보기
2. 내부에서 자동으로 끊어주더라도, 이러한 등록은 필요하지 않을 때 수동으로 끊어주는 습관을 가지자.
3. 또한 이 등록을 onCreate가 아닌 onViewCreated에서 하면 좋겠다. -> 또한 onDestroyView에서 끊어주자.

2024-06-05 09:13 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            launch {
튜터 님 피드백

지금과 같은 패턴은 잘 쓰지 않는다. 매 Flow마다 viewLifecycleOwner.lifecycleScope.launch를 호출하는 것이 좋겠다.
또한 자식 하나가 취소됐을 때, 같은 부모에 속한 다른 자식도 취소될 위험을 안고 갈 필요가 없다.

2024-06-05 11:28 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            launch {
[refactor: lifecycleScope을 개별적으로 분리](https://github.com/MeetUpEat/Rice/pull/14/commits/2706b0ad6c543f7702ad260e5a85f0d59760a55b)

2024-06-05 11:29 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
[refactor: ImageUiState 삭제](https://github.com/MeetUpEat/Rice/pull/14/commits/dae167e001dd34639818abe40773faba7dfe9a74)
[fix: ImageUiState 삭제 관련 누락된 부분 처리](https://github.com/MeetUpEat/Rice/pull/14/commits/a033083eb55855f7e1f5feb151d4ad4c321e6884)

2024-06-05 12:03 UTC, rlaxodud214 approved these changes
고생하셨습니다!!

2024-06-05 13:33 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +class ProfileFragment : BaseFragment<FragmentProfileBinding>(FragmentProfileBinding::inflate) {
refactor: BaseFragment 삭제

2024-06-05 13:41 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +        }
[refactor: onBackPressedCallback onDestroyView 시점에 연결 끊어주기](https://github.com/MeetUpEat/Rice/pull/14/commits/30487f847ee6b1983124bd395c623908b490780a)

2024-06-05 13:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>  @Parcelize
MeetingListFragment, profileEditFragment으로 action을 이용해 이동할 때, 필요해서 설정했습니다.
튜터 님 피드백에 따라 전달하기 위한 별도의 클래스로 변환한 후 전달하도록 수정하겠습니다.

2024-06-05 13:43 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/UserUiState.kt
>          val Empty = UserUiState(
Empty를 삭제하는 것으로 처리

2024-06-05 15:54 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/ImageUiState.kt
> +data class ImageUiState(
[refactor: UiState와 Action에 전달하기 위한 클래스 분리](https://github.com/MeetUpEat/Rice/pull/14/commits/cfe46d494cf6c3a7d658682f5e6bbc14202c1d53)

[refactor: UiState와 Action에 전달하기 위한 클래스 분리](https://github.com/MeetUpEat/Rice/pull/14/commits/f3f94ae2939f1610677eecf45b8f4f5eb8ed8adf)

2024-06-05 16:16 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +        val visibility = if (isVisible) View.VISIBLE else View.GONE
[refactor: visibility를 if-else 대신 확장 함수로 변경](https://github.com/MeetUpEat/Rice/pull/14/commits/972fb94aca4e31c75905cfc33d178f496a18392f)

2024-06-05 17:22 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/profile/ProfileFragment.kt
> +            }
[refactor: 프로필 화면에 필요한 데이터를 한 개의 State로 관리하도록 수정](https://github.com/MeetUpEat/Rice/pull/14/commits/05082d1e620794cb89cf4c5e487d8033d47d7951)

2024-06-05 17:24 UTC, merged