Feat/#11 notification fragment & ui
MeetUpEat/Zipbab pull request #17
Opened 2024-06-02 07:32 UTC by kory0115

close #11 
## (필수) 기능 구현 목록

알림 페이지 ui 및 muti-recyclerview 기능 구현

- 구현 목록

## (필수) 스크린샷

https://github.com/MeetUpEat/Rice/assets/124674637/8558fd89-97e8-422d-adc9-938ff46c366c

## (선택) Issue 

- 한 줄 요약
- 세부 내용

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

-전체적인 코드구성

## 참고사항

-navi fragment 에서 처음 시작값을 notificationfragment로 설정해주세요

-recyclerview를 띄워주기 위해서 다음값을 initViews안에 넣어주세요

itemList.add(NotificationType.MainNotification(dec = "공지안내드립니다.", uploadDate = "6시간전"))
        itemList.add(
            NotificationType.UserNotification(
                dec = "...가 모임에 참가 하였 습니다.",
                uploadDate = "30초전"
            )
        )

2024-06-02 11:50 UTC, DoTheBestMayB requested changes
1. 여기서 작성해주신 코드에서도 이전에 남겨드린 코드 리뷰와 겹치는 내용들이 많습니다.
우선 https://github.com/MeetUpEat/Rice/pull/10 에 남겨드린 코드 리뷰를 보고 수정해주신 후, 이 PR에 작성하신 코드도 수정해주세요.
2. 저희 팀이 지향해야 하는 목표는 단순히 기능만 구현하는 것이 아니라, 유지 보수성이 좋고 공식 문서 가이드를 따르는 우아한 코드를 작성하는 것이라고 생각합니다. 구글에 한글로 검색하면 나오는 학습 블로그에 적혀있는 코드를 참고하지 마시고, 공식 문서를 참고해서 구글에서 권장하는 코드는 무엇인지 고민하면서 의식적으로 코드를 작성하시면 실력 향상에 많은 도움이 됩니다.

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/KaKaoService.kt
네트워크 관련 파일은 Data 모듈에 있어야 합니다.

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/notientity/DownloadTokenEntity.kt
> +data class DownloadTokenEntity(
Entity는 데이터베이스에 사용하는 데이터 클래스에만 붙이기로 했습니다.

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/notientity/DownloadTokenEntity.kt
> +    val updated_at: DateTime
camelCase를 준수해주세요.

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    }
1. RecyclerView ViewHolder에 대한 개념을 학습하고 다시 작성해주세요.
2. inner 키워드는 무엇이고 언제 사용할까요?

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +): RecyclerView.Adapter<RecyclerView.ViewHolder>() {
RecyclerView adapter 구현 방법에 대해 학습하신 후, ListAdapter로 migration 해주세요.

2024-06-02 11:50 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_notification.xml
> +    </androidx.appcompat.widget.Toolbar>
Appcompat이 아닌 Material component를 사용해주세요.

2024-06-02 12:00 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +): RecyclerView.Adapter<RecyclerView.ViewHolder>() {
제 실력으로는 ListAdapter쓰면서 muti-view type 구현은 힘들것같습니다.

2024-06-02 12:04 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/KaKaoService.kt
[fix: retrofit관련부분 data 파일로 이동](https://github.com/MeetUpEat/Rice/pull/17/commits/79f1815657a7e16fff4292b8055c520a30dbb56b)

2024-06-02 12:07 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/notientity/DownloadTokenEntity.kt
> +data class DownloadTokenEntity(
[fix: data class 이름 변경](https://github.com/MeetUpEat/Rice/pull/17/commits/79e4acdd3836a3b050e8652b6db1e9e13f61bcb2)

2024-06-02 12:22 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/kakaonoti/notientity/DownloadTokenEntity.kt
> +    val updated_at: DateTime
[fix: camelCase로 수정](https://github.com/MeetUpEat/Rice/pull/17/commits/6d070466c29953cc54c3823b664b6a6d47856557)

2024-06-02 12:28 UTC, kory0115 commented on app/src/main/res/layout/fragment_notification.xml
> +    </androidx.appcompat.widget.Toolbar>
[fix: material component로 변경](https://github.com/MeetUpEat/Rice/pull/17/commits/1f06d3fb02f76b3ca9848ace888d34e14fc5f3e7)

[fix: ImageView 변경](https://github.com/MeetUpEat/Rice/pull/17/commits/76689e794638415c3f083f34a11f792c285ef34d)

2024-06-03 10:53 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +): RecyclerView.Adapter<RecyclerView.ViewHolder>() {
[fix: Adapter -> ListAdapter로 변경](https://github.com/MeetUpEat/Rice/pull/17/commits/d2ab6756a734b6d7db74b891dbe4db83e0fcc0ef)

2024-06-03 10:53 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    }
[fix: Adapter -> ListAdapter로 변경](https://github.com/MeetUpEat/Rice/pull/17/commits/d2ab6756a734b6d7db74b891dbe4db83e0fcc0ef)

2024-06-03 13:39 UTC, rlaxodud214 requested changes
여기도 컴포넌트의 id 네이밍 컨벤션에 따라 수정해주시면 좋겠습니다.

2024-06-03 13:39 UTC, rlaxodud214 commented on data/src/main/java/com/bestapp/rice/data/notification/KaKaoService.kt
> +        @Header("Authorization") key: String = "어드민 키",
okHttpClient의 Interceptor를 이용하여 중복된 헤더 값을 제거할 수 있을 것 같습니다!

2024-06-03 13:39 UTC, rlaxodud214 commented on data/src/main/java/com/bestapp/rice/data/notification/NotificationKey.kt
> +    @Json(name ="color")val color: String,
[필수] 코드 정렬 해주시면 좋겠습니다!

2024-06-03 14:30 UTC, kory0115 commented on data/src/main/java/com/bestapp/rice/data/notification/KaKaoService.kt
> +        @Header("Authorization") key: String = "어드민 키",
머지한후에 브랜치 파서 fcm작업 할떄 수정하겠습니다.

2024-06-03 14:31 UTC, kory0115 commented on data/src/main/java/com/bestapp/rice/data/notification/NotificationKey.kt
> +    @Json(name ="color")val color: String,
fcm작업할떄  브랜치 파서 작업하겠습니다.

2024-06-05 03:21 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셧습니다.

2024-06-05 03:21 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +class NotificationAdapter(
혹시 그때 참고 링크 드렸던게 도움이 되었을까용?
ListAdapter로 구현하시느라 고생하셨습니당^^

2024-06-05 03:50 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +class NotificationAdapter(
네 그떄 링크주신거 코드 참고해서 만들었습니다.

2024-06-05 09:46 UTC, DoTheBestMayB requested changes

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/build.gradle.kts
> +        buildConfigField("String", "KAKAO_ADMIN_KEY", getValue("kakao_admin_url"))
해당 키 값 discord 계정-및-key 공유 채널에 공유해주세요!

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    }
[필수]
이 코드에 논리적인 오류가 있어 보입니다. 또한 ListAdapter가 제공하는 submitList 함수를 사용하면 더 간단하게 구현할 수 있습니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    inner class ViewHolderMain(private val binding: ViewholderMainNotificationBinding) : RecyclerView.ViewHolder(binding.root) {
[선택] inner는 필요하지 않으면 지양해야 합니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +            findNavController().popBackStack()
[선택같은 필수]
권한이 없을 때, 화면을 pop하도록 설정할 경우, 사용자가 한 번 권한을 거부하면 해당 화면에 진입할 때마다 이유를 알 수 없는 상태로 계속 이전 화면으로 돌아가는 경험을 하게 되며, 현재 코드에서 이것을 해결할 수 있는 방법은 사용자가 직접 설정 창에 들어가서 권한을 수정하는 방법 밖에 없습니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
[필수⚠️]
1. API 33 미만인 기기에 대한 권한 처리가 누락되어 있습니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +                //TODO check dialog
[필수⚠️]
1. 사용자가 한 번 권한을 거부한 이후에 대응되는 코드가 누락되어 있습니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +        ) //firestore에서 값을 받아올 부분 추후에 viewModel에서 가져올예정
테스트를 위한 값들이 남아 있습니다.

2024-06-05 09:46 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationViewModel.kt
> +        )
1. 키 값이 노출되어 있는 것 같습니다.
2. 현재 dev에 있는 repository를 이용하도록 수정하면 좋겠습니다.

2024-06-05 09:57 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    }
이코드 recyclerView에서 swipe기능추가를위해넣은 코드입니다

2024-06-05 10:20 UTC, kory0115 commented on app/build.gradle.kts
> +        buildConfigField("String", "KAKAO_ADMIN_KEY", getValue("kakao_admin_url"))
공유했습니다.

2024-06-05 10:21 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +            findNavController().popBackStack()
알림을 권한을 켜지않았을경우에는 알림 리스트가 보이지않도록 수정하였습니다

2024-06-05 10:23 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    }
removeItem 함수를 호출하는 곳에서 아래와 같이 변경한 후 잘 되는지 테스트 해보시겠어요?

'''kotlin
itemList.removeAt(position)
adapter.submitList(itemList)
'''

2024-06-05 10:24 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationViewModel.kt
> +        )
[fix: 알림 권한 처리 및 예외처리](https://github.com/MeetUpEat/Rice/pull/17/commits/75330163eebbcd84e97a96758d793e41a446f643)

현재 프로젝트 merge후에 브랜치 새로파서 마저 수정하겠습니다.

2024-06-05 10:24 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +        ) //firestore에서 값을 받아올 부분 추후에 viewModel에서 가져올예정
[fix: 알림 권한 처리 및 예외처리](https://github.com/MeetUpEat/Rice/pull/17/commits/75330163eebbcd84e97a96758d793e41a446f643)

2024-06-05 10:27 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
[fix: 알림 권한 처리 및 예외처리](https://github.com/MeetUpEat/Rice/pull/17/commits/75330163eebbcd84e97a96758d793e41a446f643)

2024-06-05 10:27 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +                //TODO check dialog
[fix: 알림 권한 처리 및 예외처리](https://github.com/MeetUpEat/Rice/pull/17/commits/75330163eebbcd84e97a96758d793e41a446f643)

2024-06-05 10:41 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +            findNavController().popBackStack()
[선택]
안드로이드 권장 사항으로는 필요한 권한이 거부된 경우 사용자가 앱 설정 창에 직접 들어가서 수정하도록 Dialog 창을 띄어 유도해야 합니다.

https://github.com/MeetUpEat/Rice/blob/3420fee9591cc1c5a624ed5005887671181688fa/app/src/main/java/com/bestapp/rice/ui/profileimageselect/permission/ImagePermissionManager.kt#L37-L69

2024-06-05 10:44 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
> +                //TODO check dialog
shouldShowRequestPermissionRational 함수를 사용하는 이유는 사용자가 2번 거부하면 더 이상 권한을 요청할 수 없고, 사용자가 직접 설정 창에 들어가야 해서 그렇습니다.

https://github.com/MeetUpEat/Rice/blob/3420fee9591cc1c5a624ed5005887671181688fa/app/src/main/java/com/bestapp/rice/ui/profileimageselect/permission/ImagePermissionManager.kt#L107-L117

2024-06-05 10:46 UTC, DoTheBestMayB approved these changes

2024-06-05 10:54 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    inner class ViewHolderMain(private val binding: ViewholderMainNotificationBinding) : RecyclerView.ViewHolder(binding.root) {
저도 nested class로 쓰라는 피드백을 받았던 적이 있네요
관련 [게시글](https://velog.io/@plashdof/Kotlin-Inner-Class-vs-Nested-Class) 남길게요!

2024-06-05 13:26 UTC, rlaxodud214 approved these changes

2024-06-05 13:26 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationAdapter.kt
> +    companion object {
Kotlin 컨벤션의 Class부분 순서에 따르면, companion object는 현재 코드에서 최하단에 위치하는 것이 정석입니다!!

2024-06-06 06:00 UTC, merged