Feat/#16 recruitment fragment
MeetUpEat/Zipbab pull request #24
Opened 2024-06-04 08:19 UTC by kory0115

close #16 
## (필수) 기능 구현 목록

- 모임 작성 페이지 ui 구현
- 작성 페이지 기능 일부 구현

## (필수) 스크린샷

(https://github.com/MeetUpEat/Rice/assets/124674637/c7a24d0c-636a-474e-8491-9a6c2de0efba)

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

-전반적인 코드 구성및 디자인

## 참고사항

-navi fragment시작값을 recruitmentfragment로 변경해주세요

2024-06-07 02:22 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +class RecruitmentFragment : BaseFragment<FragmentRecruitmentBinding>(FragmentRecruitmentBinding::inflate) {
현재 dev에 모든 Fragment는 BaseFragment를 상속받고 있지 않습니다.

종성님이 일괄적으로 모든 Fragment를 수정하신 걸로 알고 있어요!

pull이 덜 된것인지 원인은 파악하지 못했습니다.

[필수] 
우선 BaseFragment 상속을 제거한 뒤, 생명주기에 맞게 Binding을 세팅해주시고,
Hilt 적용까지 해주시면 좋겠습니다.

2024-06-07 02:43 UTC, rlaxodud214 reviewed
UI에 대한 PR이고, 기능 구현은 이 pr이 dev에 merge된 이후, 다른 브랜치에서 해주시는 게 맞을까요?

2024-06-07 02:53 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_recruitment.xml
> +                    android:layout_marginHorizontal="@dimen/default_margin20"
[필수] ChipGroup에 margin이 제대로 적용되지 않았습니다.

해당 코드가 상위 컴포넌트 HorizontalScrollView의 속성으로 이동되어야 합니다.

<p align="center">
   <img src="https://github.com/MeetUpEat/Rice/assets/52482206/cb4f5526-05ce-4983-9b41-3071de431fe6" height=700px align="left">

   <figcaption align="center"></figcaption>
</p>

2024-06-07 02:55 UTC, rlaxodud214 commented on app/src/main/res/values/colors.xml
> +    <color name="clr_8A8A8A">#8A8A8A</color>
[선택] 어떤 컬러인지 또는 어디에 쓰는 컬러인지 명확하면 좋을 것 같습니다.

2024-06-07 03:09 UTC, rlaxodud214 requested changes
[필수]
1. 모든 Fragment가 BaseFragment를 상속 받는 부분 해결(pull 이슈)

2024-06-07 03:09 UTC, rlaxodud214 commented on app/src/main/res/values/styles.xml
> +    <style name="Widget.Chip" parent="Widget.MaterialComponents.Chip.Choice">
별도의 스타일로 빼서 작업하셨군요!! 좋습니다 👍 

저도 다음부터 고려해볼게요!

2024-06-07 03:09 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +class RecruitmentFragment : BaseFragment<FragmentRecruitmentBinding>(FragmentRecruitmentBinding::inflate) {
[필수] 
pull 문제인 것 같습니다. 
#16 브랜치의 모든 Fragment가 BaseFragment를 상속받고 있어서 반드시 수정한 뒤, merge 해야합니다!

2024-06-07 03:33 UTC, yoonchanchoi requested changes
머지에 에러가 난 부분이 있어서 확인 해보셔야 될 것 같아용
아마 dev 패치 내용이 안들어 간게 아닐까 합니다.

2024-06-07 03:33 UTC, yoonchanchoi commented on app/src/main/res/values/colors.xml
> +    <color name="clr_8A8A8A">#8A8A8A</color>
저도 현재 조금 애매해서 저 컬러가...고민입니다.
조금 다용도로 쓰이는 곳이있어서...

2024-06-07 03:33 UTC, yoonchanchoi commented on app/src/main/res/values/styles.xml
> +    <style name="Widget.Chip" parent="Widget.MaterialComponents.Chip.Choice">
이렇게 뺄 수도 있군요.
chip도 가능하군요 
최근에 floatingactionbutton을 뺀 적은 있는 chip도 되는지는 몰랐습니당^^😁

2024-06-07 03:33 UTC, yoonchanchoi commented on app/src/main/res/values/strings.xml
> +    <string name="recruit_text">모집 글쓰기</string>
혹시 해당 어느 화면에서 쓰는지 표시해주시면 좋을 것 같아용~~😀

2024-06-07 04:14 UTC, DoTheBestMayB approved these changes

2024-06-07 04:14 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +            //firestore에 값저장
[선택]
현재 data 레이어 부분이 모두 merge 되었기 때문에, 해당 기능 이번 branch에 함께 구현해주시면 좋겠습니다!

나중으로 미루면, 이 코드가 dev에 합쳐지고 다른 화면과 연계해서 기능을 테스트할 때
이 기능 구현이 누락된 건지, 진행 중인지, 논리적 오류인지 확인하는 데 시간이 소요됩니다

2024-06-07 04:14 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +    private fun chipGroupType(type: ChipType) {
[선택] 각 타입 body가 비어있는데 해당 로직이 미구현이어서 일까요?

2024-06-07 04:22 UTC, rlaxodud214 commented on app/src/main/res/values/colors.xml
> +    <color name="clr_8A8A8A">#8A8A8A</color>
용도가 다양하다면 색상값 (ex gray_light) 으로  표기해보는 건 어떨까요?

2024-06-07 10:03 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +class RecruitmentFragment : BaseFragment<FragmentRecruitmentBinding>(FragmentRecruitmentBinding::inflate) {
네 이거 hilt적용전 basefragment 변경 전에 완성한 브랜치라 그런것같습니다.

2024-06-07 10:04 UTC, kory0115 commented on app/src/main/res/values/colors.xml
> +    <color name="clr_8A8A8A">#8A8A8A</color>
chip그룹 관련된 색입니다.

2024-06-07 23:26 UTC, kory0115 commented on app/src/main/res/layout/fragment_recruitment.xml
> +                    android:layout_marginHorizontal="@dimen/default_margin20"
[fix: 기본 로ì§ 수저ã정](https://github.com/MeetUpEat/Rice/pull/24/commits/7175df0f2d40b8bfd260deab2c10aff1e098a0f9)

2024-06-07 23:26 UTC, kory0115 commented on app/src/main/res/values/styles.xml
> +    <style name="Widget.Chip" parent="Widget.MaterialComponents.Chip.Choice">
[fix: 기본 로ì§ 수저ã정](https://github.com/MeetUpEat/Rice/pull/24/commits/7175df0f2d40b8bfd260deab2c10aff1e098a0f9)

2024-06-08 09:24 UTC, rlaxodud214 commented
#16 브랜치에서 git pull origin dev 수행해주셔야 합니다.

2024-06-08 10:36 UTC, rlaxodud214 approved these changes
협의사항
- 데이터 연동이 완성되지 않아 "작성 완료" 버튼 눌러도 서버에 모임 정보가 추가되지 않습니다.
- 토스트 메세지를 통해 "해당 기능은 미구현 상태 입니다"를 띄워줄 예정입니다.

2024-06-09 05:16 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셨습니다.

2024-06-09 11:12 UTC, merged