Feat/#13 검색 화면 UI와 기본 필요한 동작 구현
MeetUpEat/Zipbab pull request #26
Opened 2024-06-04 17:31 UTC by yoonchanchoi

## (필수) 기능 구현 목록

- 검색 화면 UI와 기본 필요한 동작 구현

## (필수) 스크린샷

- <img src="https://github.com/MeetUpEat/Rice/assets/74814647/1a932143-bb98-4184-835b-9504f9e8f976" width="250" height="400">
- <img src="https://github.com/MeetUpEat/Rice/assets/74814647/775a4ff8-607c-4c87-aa59-baee4df704f8" width="200" height="400">

## (선택) Issue 

- 검색 화면 UI와 기본 필요한 동작 구현
- fake 데이터를 이용하여 더미 데이터로 넣었습니다. 데이터가 없을 시 이미지 화면, empty text 노출 검색 시 데이터 정보 제공 아이템 클릭 시 해당 meeting데이터의 호스트 값을 체크 하여 다음 뷰로 이동

2024-06-05 23:02 UTC, kory0115 reviewed
수고하셨습니다.

2024-06-05 23:02 UTC, kory0115 approved these changes

2024-06-05 23:04 UTC, kory0115 reviewed
app/src/main/java/com/bestapp/rice/model/FilterUiState.kt
app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
app/src/main/res/values/colors.xml
여기서 충돌 일어난다고 하네요 한번만 확인해주세요

2024-06-07 01:20 UTC, yoonchanchoi commented
말씀하신 충돌 부분 없어졌습니당^^

2024-06-07 03:26 UTC, rlaxodud214 approved these changes

2024-06-07 03:26 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +    }
destroyView에서 Adapter null 처리가 누락된 것 같습니다!

2024-06-07 03:26 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
> +    }
단일 표현식으로 아래와 같이 간소화할 수 있을 것 같습니다

```kotlin
fun getMeetingDocumentId() = this.meetingDocumentId
```

2024-06-07 03:26 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_search.xml
> +        android:layout_marginTop="15dp"
기존에 4의 배수만을 사용하기 위해 정의해둔 dimen_margin(4, 8, 12, 16, 20)으로 변경하면 좋을 것 같아요

2024-06-07 03:26 UTC, rlaxodud214 commented on app/src/main/res/layout/item_search.xml
> +        android:layout_height="72dp"
dimen에 정의된 값으로 수정해주시면 좋을 것 같습니다.

```kotlin
<dimen name="profile_image72">72dp</dimen>
```

2024-06-07 04:35 UTC, DoTheBestMayB requested changes

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
[필수]
view가 viewModel에 있는 값을 꺼내서 사용하는 것은 안티 패턴입니다.
viewModel에 event를 전달해서 처리되도록 수정해주세요!

(아래 3개 모두 동일)

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                        Log.e("cyc", "키보드 검색")
로그가 남아있네요😀

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_search.xml
> +    <EditText
maxlines로 엔터로 인한 줄바뀜을 막으면 ui적으로 더 좋겠습니다

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +        viewModel.setMeetingDocumentId(meetingUiState.meetingDocumentID)
이 함수와 아래 함수가 항상 같이 불린다면, 한 개로 합치는 건 어떨까요?

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
> +    fun getMeetingDocumentId(): String {
[필수]
지양해야 하는 패턴입니다!
MVVM에 맞지 않는 코드입니다

2024-06-07 04:35 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_search.xml
> +        android:layout_height="300dp"
dp보다는 guideline을 이용해 전체 화면의 특정 비율을 차지하도록 하면 더 좋겠습니다

2024-06-08 11:07 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +    }
2c2c2bfb664c35213fe834e487500db1223924c1

2024-06-08 11:07 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
> +    }
528c1955b31edf1d910fbb20da3324c5bcbcacbf

2024-06-08 11:07 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_search.xml
> +        android:layout_marginTop="15dp"
39abf361ed9c31123e5b7387a4c2c9a82ced94f6

2024-06-08 11:08 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                        Log.e("cyc", "키보드 검색")
a9502136070b50883186494d79ea3afc64a5bb18

2024-06-08 11:08 UTC, yoonchanchoi commented on app/src/main/res/layout/fragment_search.xml
> +    <EditText
fab13bbc0d664af784f532dea2c4d198f4f32f8a

2024-06-08 11:08 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchViewModel.kt
> +    fun getMeetingDocumentId(): String {
83867d86a27aee3eb37977a0a67fa450e1cf8423

2024-06-08 11:14 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
ViewModel에서 View의 값을 꺼내쓰는 것은 일반적으로 안티 패턴이 아닌 것으로 알고 있습니다. 
특히 해당 값이 event의 navigation의 방향을 정해주는 것을 직접적인 값을 꺼내 쓰는 것이 아니며, 해당 안티 패턴중에 LiveData를 직접적으로 꺼내 쓰는 것을 지양하는 것으로 알고 있습니다. View에 해당 ViewModel의 값을 꺼내 쓰는 것이 가장 기본적인 mvvm 패턴의 예로 알고 있습니다. 

혹시 다른 방법이 있다면 어떤 방식으로 해당 부분의 데이터를 꺼내 써야 되는지 알려 주실 수 있나용?

2024-06-08 11:14 UTC, yoonchanchoi commented on app/src/main/res/layout/item_search.xml
> +        android:layout_height="72dp"
6b8fba96b9eb31b82a525cec94e980d8a54b253e

2024-06-08 11:49 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
전에 이런 코드를 작성했다가 세진 튜터 님께 피드백을 받은 적이 있어서요.

제 생각으로는, view가 viewModel의 함수 호출로 데이터를 직접 리턴 받으면 단방향 흐름이 아니게 될 것 같아서요
https://developer.android.com/topic/architecture#unidirectional-data-flow

월요일 날 세진 튜터 님에게 여쭤보고 공유해주세요!

2024-06-08 13:31 UTC, DoTheBestMayB approved these changes

2024-06-10 03:44 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
46d6d871ff97f3155aab0fa1bb77760cda71268c
안티 패턴이라기 보다는 해당 flow쓰기 때문에 한번에 보내주는 편이 더 깔끔한 코드라고 하시더군요^^

2024-06-10 03:48 UTC, merged

2024-06-10 03:53 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
그러면 LiveData, Flow 값이 아니라면 view에서 ViewModel에 있는 값을 직접 꺼내는 행위는 괜찮은 건가요?

meetingDocumentId는 View가 searchMeeting state에 있는 값을 observing으로 얻은 후 ViewModel에 저장한 것인데, observing을 통해 얻은 값일지라도, View가 직접 저장한 것은 사용해도 되는 건가요?

2024-06-10 04:14 UTC, DJDrama commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
@DoTheBestMayB collect 내에서 viewmodel getter를 쓰는건 set이 아니라 양방향은 아니겠지만 thread safe 하지 않아서 위험할 것 같습니다.

2024-06-10 04:43 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
@DJDrama collect 내부가 아니라면 괜찮은 건가요? ViewModel에 있는 값(status의 특정 파라미터 한 개 또는 property 값)이 필요한 순간에 ViewModel에 onXxx 와 같은 함수를 호출해서 필요한 값을 observing 형태로 얻도록 구현했었는데, 단방향 흐름을 위해서, 필요한 데이터를 이렇게 빙 돌아서 얻는 게 맞는지 궁금했습니다.

그래서, UI에 표시하는 데 필요한 데이터는 collect 시점에 View의 로컬 property로 저장해서 사용했습니다.

https://github.com/MeetUpEat/Rice/blob/dev/app/src/main/java/com/bestapp/rice/ui/setting/SettingFragment.kt#L94-L103

이렇게 한 이유는
1. setListener 함수에서 action에 지정할 변수 값이 필요한데, 이 설정을 collect block에서 호출하는 것은 어색하다고 생각했습니다.
2. Navigation과 관련된 데이터는 ViewModel이 아닌 View에서 관리해야 한다는 공식 문서 가이드에 근거해서 이렇게 작성해도 된다고 판단했습니다.

> ViewModel이 화면 A에서 화면 B로 가기 위한 state를 만들었을 때, 사용자의 의사와 관계없이 화면 B로 전환되는 것을 방지하기 위해 다른 화면으로 전환해도 되는지를 나타내는 state가 필요하다. Navigation logic은 ViewModel 아닌 UI와 관련된 로직이기 때문에, 이 state는 UI에서 관리되어야 한다.
> https://developer.android.com/topic/architecture/ui-layer/events#navigation-events-destination-back-stack

2024-06-10 06:35 UTC, DJDrama commented on app/src/main/java/com/bestapp/rice/ui/search/SearchFragment.kt
> +                            val meetingDocumentID = viewModel.getMeetingDocumentId()
@DoTheBestMayB meetingid가 viewmodel에 저장되어있으니 flow를 사용한다면, emit을 같이 해주는게 맞습니다. 단 일부 코드만 봐서는 전체 맥락을 파악할 수가 없어서 정확히 뭘 구현하고자 하는지는 모르겠습니다. 애초에 리팩토링이 필요할 것 같긴 합니다.