Feat/#37 notification fragment
MeetUpEat/Zipbab pull request #38
Opened 2024-06-06 14:50 UTC by kory0115

close #37 

dev merge용 브랜치입니다.

2024-06-06 23:59 UTC, rlaxodud214 approved these changes

2024-06-07 00:15 UTC, DoTheBestMayB requested changes
[fix: 병합 문제해결(](https://github.com/MeetUpEat/Rice/pull/38/commits/66b27467564dcf8fbbfaa373699baef368b59d69)

dev에 있는 것을 merge 하면 기존 코드는 Files Changed에 포함되지 않아야 하는데, 이 커밋이 이상합니다.

2024-06-07 00:15 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/App.kt
> +)
이 코드는 이제 삭제해도 됩니다.

2024-06-07 00:20 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/App.kt
> +)
val Context.dataStore by preferencesDataStore(
    name = "AppSettings",
)이부분을 삭제하라는 뜻인가요?

2024-06-07 00:38 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/App.kt
> +)
네 주석이랑 코드 모두 삭제해주시면 됩니다!

2024-06-07 00:39 UTC, DoTheBestMayB approved these changes

2024-06-07 00:51 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/App.kt
> +)
수정했습니다

2024-06-07 01:15 UTC, yoonchanchoi approved these changes
구현 하시느라 고생하셨습니다.
TODU쪽 리뷰 하나 남겼어용^^

2024-06-07 01:15 UTC, yoonchanchoi commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationViewModel.kt
> +class NotificationViewModel(
해당 부분은 TODO 남겨주시면 나중에 구현할 때 찾기 편하실 것 같아용~~😁

2024-06-07 01:19 UTC, merged