fix: User dataclass fix and and server connect
MeetUpEat/Zipbab pull request #49
Opened 2024-06-09 04:20 UTC by kory0115

close #47 
## (필수) 기능 구현 목록

- user 데이터 클래스 수정및 firestore연결

## (필수) 스크린샷

![image](https://github.com/MeetUpEat/Rice/assets/124674637/578feebd-c374-43e4-9a11-c7e1c1df76bc)

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

더 추가 해야할것같은부분 위주로 봐주세요

## 참고사항

없음?

2024-06-10 10:27 UTC, rlaxodud214 commented on data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
> +    override suspend fun signUpUser(user: User): Pair<String, Boolean> {
userDocumentId값을 반환하므로 Boolean 타입은 제거해도 될 것 같습니다.

반환 값이 없는 메서드는 성공 여부를 알기 힘들고, 예외 처리가 어려울 것 같아 추가해뒀었습니다!

2024-06-10 10:41 UTC, rlaxodud214 approved these changes

2024-06-10 10:41 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
> +sealed interface NotificationUiState {
해당 코드는 NotificationUI가 되어야 하고, XXXUIState는 아래와 같이 되야합니다.
@DoTheBestMayB 제가 이해한 게 맞을까요?

```kotlin
data class NotificationUIState(
    val notificationUis: List<Notification>
    ... // 알림 화면에서 필요한 상태값등
)
```

2024-06-10 10:42 UTC, kory0115 commented on data/src/main/java/com/bestapp/rice/data/repository/UserRepositoryImpl.kt
> +    override suspend fun signUpUser(user: User): Pair<String, Boolean> {
boolean값 받아서 fragment쪽에서 예외처리하는용도로 사용중입니다.

2024-06-10 10:43 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
> +sealed interface NotificationUiState {
제가 sealed class로 사용해도되는지 질문헀었는데 사용해도 괜찮을것같다고 해주셨습니다

2024-06-10 10:52 UTC, DoTheBestMayB requested changes

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
> +import com.bestapp.rice.data.model.remote.NotificationType
사용하지 않는 import인 것 같아요. 삭제해주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +        }
[필수]
ViewModel에서 observing으로 가져온 값을 로컬 property에 저장하지 마시고, 필요한 함수에 호출해서 값을 바로 넣어주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +    private var hostTemperature : Double = 0.0
[필수] viewModel에서 observing을 통해 값을 가져와야 합니다. 여기서도 가지고 있으면 Single Source of Truth에 어긋납니다.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
> +    fun getHostInfo(userDocumentId: String) = viewModelScope.launch {
launch 블록의 반환 값은 Unit이 아니기 때문에 block 내부로 옮겨주세요. ( 아래 함수들도 동일)

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
> +    val getDocumentId : LiveData<String> = _getDocumentId
1. 변수 -> 함수 순서대로 나열해주세요.
2. Flow로 변환해주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
> +            getHostInfo(it.ifEmpty { "" })
이 코드에서 ifEmpty는 불필요합니다.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +        )
빈 값을 굳이 변수로 선언해둘 필요는 없어 보입니다.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            if(it.second) {
[필수] Pair는 코드를 작성한 사람이 아니면, 해당 변수가 어떤 것인지 알 수 없기 때문에 지양해야 합니다.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +                signUpViewModel.saveDocumentId(it.first)
[필수]
1. 저장이 완료되지 않은 시점에 SignUpFragment가 파괴되면 어떻게 될까요?
2. 인터넷이 연결되지 않은 상태에서 이 로직을 실행하면 어떻게 될까요?

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            val randomUUID = (1..10000000).random()
1. 그냥 random을 호출하면 일정한 패턴이 있는 random 값이 생성됩니다. `System.currenttimemillis`가 시드로 입력된 Random을 사용해주세요.
2. Q면접관. 100만 명보다 더 많은 사람이 가입하면 어떻게 되나요? A. 저희 앱은 학습 목적의 앱이라 그런 일은 발생하지 않기 때문에 고려 안 했습니다. Q면접관. ............... 나가세요
3. uuid 중복 검사 로직이 없습니다.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  if(binding.etvName.length() > minNumber) {
minNumber 대신 res/values/user_info.xml에 있는 값을 사용해주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                      binding.bCheck.isVisible = true
이 코드 아래에 있는 문자열들 strings.xml로 빼주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpViewModel.kt
> +    val isSignUpState : LiveData<Pair<String, Boolean>> = _isSignUpState
Flow로 바꿔주세요.

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_sign_up.xml
1. TextInputLayout에서 제공하는 기능을 이용하면 tv_compare_result를 없앨 수 있습니다.
https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md

2024-06-10 10:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>          Linkify.addLinks(binding.tvTerms, pattern, "", null, mTransform)
[필수]
https://github.com/MeetUpEat/Rice/pull/10#discussion_r1622271990

누락되지 않도록 TODO List를 메모장 또는 Github Backlog에 관리하시면 좋겠습니다.

2024-06-10 10:54 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
> +sealed interface NotificationUiState {
@rlaxodud214 네 맞습니다.

또한 UI라고 되어 있는 것들은 Info로 변경해야 합니다.

2024-06-10 14:36 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/model/NotificationUiState.kt
> +import com.bestapp.rice.data.model.remote.NotificationType
[fix: comment내용반영](https://github.com/MeetUpEat/Rice/pull/49/commits/eed4d36380d55d4b16534613d60fbe7d8e945eed)
사용하지않는 import 삭제했습니다.

2024-06-10 14:37 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +        }
만약 initViews안쪽에서 넣어주는 값이면 initViews안에 var로 생성하라는 말씀이신가요?

2024-06-10 14:39 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +        }
ViewModel observing을 통해 얻은 값을 hostTemperature, hostKey와 같은 값에 저장하지 말고 바로 사용해야 합니다.

var, val 값 저장 자체 XXXXXXXXXXX

2024-06-10 14:40 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +    private var hostTemperature : Double = 0.0
사용하는 함수내에서만 선언하는것으로 수정하였습니다.

2024-06-10 14:41 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentViewModel.kt
> +    val getDocumentId : LiveData<String> = _getDocumentId
flow로 변환은 코드 작성완료후 변환한다고 태영님꼐 말씀 드렸었습니다

2024-06-10 14:41 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  if(binding.etvName.length() > minNumber) {
user_info에 따로 선언후 적용했습니다

2024-06-10 14:45 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpViewModel.kt
> +    val isSignUpState : LiveData<Pair<String, Boolean>> = _isSignUpState
전체 코드 구성후 수정하겠습니다.

2024-06-10 14:45 UTC, kory0115 commented on app/src/main/res/layout/fragment_sign_up.xml
링크 참고해서 수정하였습니다.

2024-06-10 14:46 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>          Linkify.addLinks(binding.tvTerms, pattern, "", null, mTransform)
이용약관 링크도 추가로 연결해두었습니다 TODO List는 따로 메모장에 작성중입니다.

2024-06-10 14:49 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  if(binding.etvName.length() > minNumber) {
좋습니다~ min은 이상의 의미를 담고 있기 때문에, 부호를 >=로, 각 값은 1씩 증가하면 더 분명해지겠습니다.

2024-06-10 14:50 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +    private var hostTemperature : Double = 0.0
로컬 변수 자체를 선언하지 않고 구현해보세요!

2024-06-10 14:52 UTC, DoTheBestMayB commented on app/src/main/res/layout/fragment_sign_up.xml
링크는 strings.xml이 아닌 Firestore에 있는 값을 가져오도록 작성해야 합니다!

제가 작성한 코드를 참고해서 변경해보세요!

https://github.com/MeetUpEat/Rice/pull/53/files

2024-06-10 14:52 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>          Linkify.addLinks(binding.tvTerms, pattern, "", null, mTransform)
좋습니다!

링크는 strings.xml이 아닌 Firestore에 있는 값을 가져오도록 구현해야 합니다!
제가 작성한 코드를 참고해서 변경해보세요!
https://github.com/MeetUpEat/Rice/pull/53/files

2024-06-10 15:00 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            val randomUUID = (1..10000000).random()
Random(System.currenttimemillis) 이렇게 하면될까요?

2024-06-10 15:03 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            if(it.second) {
string값만 반환하도록 수정했습니다.

2024-06-10 15:25 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
> +            val randomUUID = (1..10000000).random()
네, `Random(System.currentTimeMillis())`를 class의 property로 선언하고 uuid 생성시마다 재활용하시면 됩니다!

2024-06-10 16:11 UTC, DoTheBestMayB approved these changes
이 코드가 합쳐져야 다른 코드 구현이 가능하다면, 남은 코멘트 내용들은 TODO 리스트에 적은 후, 다음 PR에서 마무리 해주세요!👍

2024-06-11 02:23 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셨습니다.

2024-06-11 02:59 UTC, merged