Feat/#32 register fragment
MeetUpEat/Zipbab pull request #67
Opened 2024-06-13 08:04 UTC by kory0115

close #32 
## (필수) 기능 구현 목록

-로그인 ui수정 및 기능구현

-회원가입 ui수정 및 기능구현

-모임 작성 페이지 ui수정 및 기능구현

## (필수) 스크린샷

![image](https://github.com/MeetUpEat/Rice/assets/124674637/a12a160b-3df4-4147-9e80-de18e7fb1161)
![image](https://github.com/MeetUpEat/Rice/assets/124674637/f1d36123-2288-41cb-b391-bc66ce5ae6b8)
![image](https://github.com/MeetUpEat/Rice/assets/124674637/eb1c5098-64e6-47c4-9ada-e99be9218bb8)

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

-잠재적으로 오류가 생길수 있는 코드 및 기능적인부분 위주로 봐주시면 감사하겠습니다.

## 참고사항

없습니다.

2024-06-13 08:42 UTC, DoTheBestMayB requested changes
로그인 화면, 회원가입 화면에서 뒤로가기 버튼이 누락되었어요.

2024-06-13 08:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  temperature = 0.0,
첫 온도는 36.5도 입니다.

2024-06-13 08:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
저장된 아이디 정보가 있으면 Remember Id가 클릭된 상태로 변경되도록 추가하면 좋겠습니다.

2024-06-13 08:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
>          }
권한 대응하는 로직 잘 구현해주셨습니다!

아래 권한이 거부된 경우에는 사용자에게 권한이 필요한 이유를 설명하는 Dialog를 보여준 후, 앱의 설정창으로 직접 이동시켜 직접 수정하도록 해야 합니다.

2024-06-13 08:42 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
1. 이미지 권한 대응이 잘못되어 있어요. 시간이 없기 때문에 PhotoPicker로 변경하시는 게 좋겠습니다!
2. 모임 위치에서 아무것도 안 입력하고 검색을 누르면 앱이 꺼집니다. `etrofit2.HttpException: HTTP 400 `
3. 각 입력 칸에 대한 제한사항이 안 걸려 있습니다. 예를 들어, 1인당 비용에 Integer를 초과하는 값 1000000000000000000000000000000 를 입력하면 앱이 런타임에 죽습니다.
4. 아무 것도 입력하지 않았을 때 앱이 죽어요.
5. 그 외 기타 등등..

2024-06-13 08:42 UTC, DoTheBestMayB commented on data/src/main/java/com/bestapp/rice/data/network/AuthInterceptor.kt
이 파일은 왜 주석처리 되어 있나요?

2024-06-13 08:57 UTC, kory0115 commented on data/src/main/java/com/bestapp/rice/data/network/AuthInterceptor.kt
authInterceptor부분과 noti쪽 interceptor를 통합해서 윤찬님께서 만들어서 넣어놓으셔서 주석처리 해달라고 하셔서 했습니다.

2024-06-13 08:59 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
이미지 권한 이 잘못되었나요? 버전에 따라 나눠지는것까지 고려했는데 어디가 부족할까요?

2024-06-13 09:00 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/notification/NotificationFragment.kt
>          }
이부분은 나머지 3주에 알림기능 구현 할떄 마저 처리하도록 하겠습니다.

2024-06-13 09:25 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
Partical Grant라는 권한이 Android 15에 추가 되었는데, 해당 권한에 대해서는 거부 되었다고 처리되어 있어요. 이 부분은 설명드리기가 좀 복잡해서 현재 단일 사진만 가져오는 상황에서는 Photo Picker로 변경하는 것이 좋아보여요.

2024-06-13 10:05 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
한번찾아보고 변경할수있으면 해보겠습니다

2024-06-13 12:30 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  temperature = 0.0,
[fix: 각 ui마다 back버튼 적용](https://github.com/MeetUpEat/Rice/pull/67/commits/a0f5b6a1dcd221388b7a3d6143ea4d184ac53600)
온도 수정하였습니다.

2024-06-13 12:31 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
[fix: 예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/1291d415afac8328927088d3b68ee1441f3afa88)
체크가 뜨도록 수정하였습니다.

2024-06-13 12:59 UTC, rlaxodud214 approved these changes

2024-06-13 12:59 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_login.xml
>              android:background="@drawable/background_edittext"
![image](https://github.com/MeetUpEat/Rice/assets/52482206/f1689f87-bbd6-4003-abee-d7a8338ffd98)
비밀번호 입력창의 UI를 보면 라인이 2개로 겹쳐져 있습니다.

이 코드 제거해주시면 좋을 것 같습니다

2024-06-13 12:59 UTC, rlaxodud214 commented on app/src/main/res/layout/fragment_recruitment.xml
>                  android:id="@+id/title_image_select"
여기에는 선택된 사진이 업로드되야하고, 
title_image에는 정적 이미지로일반 drawable 카메라 아이콘이 들어가야 할 것 같습니다.

![image](https://github.com/MeetUpEat/Rice/assets/52482206/4ffb3791-1acd-428c-936c-8bc60043c006)

2024-06-13 12:59 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
>          recruitmentViewModel.recruit.observe(viewLifecycleOwner) {
if문 내에서 Toast를 통해 "모임 모집글이 정상적으로 등록되었습니다" UI가 추가되어야 할 것 같습니다.

2024-06-13 12:59 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
>                  time = binding.timeEdit.text.toString(),
모임 날짜도 time에 포함되어야 합니다!

time값 형식 : 10/28일 오후 04:00

2024-06-13 12:59 UTC, rlaxodud214 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +                titleImage = imageValue,
이미지 링크 제대로 적용된 거 확인 됐습니다! 👍

2024-06-13 13:03 UTC, rlaxodud214 submitted a review, later dismissed
회원가입 페이지에서 "회원가입" 버튼을 누른 경우 popbackstack()을 해서 전 페이지로 돌아가는데 
세팅 페이지에서 회원가입 페이지로 진입한 경우를 고려하여, 로그인 페이지로 이동해야 할 것 같습니다.
-> 모든 backstack을 제거한 뒤, login으로 action 하면 될 것 같습니다.

2024-06-13 13:26 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/signup/SignUpFragment.kt
>                  temperature = 0.0,
올려주신 커밋에 온도 수정 내용이 없는 것 같습니다.

2024-06-13 13:37 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
작업하실 때는 상관 없으나, PR 이후 수정하시는 커밋은 코드 리뷰에서 언급한 내용만 수정한 후 커밋해서 링크 달아주세요.

2024-06-13 13:37 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
앱을 최초로 설치한 후, 체크 버튼을 누르면 체크 버튼이 다시 취소 되는 버그 있습니다.

2024-06-13 13:37 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +                titleImage = imageValue,
밑에 적어주신내용은 잘모르겠습니다 셋팅 페이지에서 회원가입 페이지로 넘어올떄 특정 값을 보내준다면 그걸로 처리 할수는 있을것같습니다.

2024-06-13 14:03 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
> +                titleImage = imageValue,
[fix:예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/169495713399d02179ad672916d1f1041dda62ec)
해결했습니다.

2024-06-13 14:03 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
>                  time = binding.timeEdit.text.toString(),
[fix:예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/169495713399d02179ad672916d1f1041dda62ec)

2024-06-13 14:03 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/recruitment/RecruitmentFragment.kt
>          recruitmentViewModel.recruit.observe(viewLifecycleOwner) {
[fix:예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/169495713399d02179ad672916d1f1041dda62ec) 추가하였습니다.

2024-06-13 14:04 UTC, kory0115 commented on app/src/main/res/layout/fragment_recruitment.xml
>                  android:id="@+id/title_image_select"
[fix:예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/169495713399d02179ad672916d1f1041dda62ec) 위치 변경해줬습니다.

2024-06-13 14:04 UTC, kory0115 commented on app/src/main/res/layout/fragment_login.xml
>              android:background="@drawable/background_edittext"
[fix:예외처리](https://github.com/MeetUpEat/Rice/pull/67/commits/169495713399d02179ad672916d1f1041dda62ec) 안보이게 설정하였습니다.

2024-06-13 15:56 UTC, yoonchanchoi approved these changes, later dismissed

2024-06-13 15:57 UTC, kory0115 commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
제가 앱삭제후 다시 실행해봤는데 오류가 없는것같습니다??

2024-06-13 19:12 UTC, rlaxodud214 approved these changes, later dismissed

2024-06-14 01:14 UTC, DoTheBestMayB approved these changes, later dismissed

2024-06-14 01:14 UTC, DoTheBestMayB commented on app/src/main/java/com/bestapp/rice/ui/login/LoginViewModel.kt
> +        }
@kory0115 
![bug](https://github.com/MeetUpEat/Rice/assets/48354989/b3333e8e-5995-406f-ab33-5d1fd07b75ab)

2024-06-14 05:02 UTC, yoonchanchoi approved these changes, later dismissed

2024-06-14 05:20 UTC, DoTheBestMayB submitted a review, later dismissed

2024-06-14 13:31 UTC, yoonchanchoi submitted a review, later dismissed

2024-06-14 13:54 UTC, DoTheBestMayB submitted a review, later dismissed

2024-06-14 14:21 UTC, yoonchanchoi approved these changes, later dismissed

2024-06-14 14:22 UTC, rlaxodud214 approved these changes, later dismissed

2024-06-14 15:10 UTC, DoTheBestMayB approved these changes

2024-06-14 15:14 UTC, rlaxodud214 approved these changes

2024-06-14 15:14 UTC, yoonchanchoi approved these changes

2024-06-14 15:17 UTC, merged