#6-setting retrofit moshi
MeetUpEat/Zipbab pull request #7
Opened 2024-05-31 05:51 UTC by rlaxodud214

## (필수) 기능 구현 목록

- retrofit, moshi 및 service 객체 생성
- 주소 검색 API 연동(repo, Impl)

## (필수) 스크린샷

![image](https://github.com/MeetUpEat/Rice/assets/52482206/4336023a-bf46-4f3b-8c71-e31d9ab70cdd)

## (선택) Issue 

- 한 줄 요약: API Call시에, RoadAddress 값이 반환되지 않음
- 세부 내용 : roadAddress 타입을 nullable 하게 처리함.
- 에러 로그 : com.squareup.moshi.JsonDataException: Required value 'roadAddress' missing at $.documents[1]

## (선택) 집중적으로 코드리뷰 받고 싶은 부분

- 아키텍쳐 구조가 이상하지 않은지 
- 패키지 구조를 어떻게 수정하면 좋을지

## 참고사항

- 팀원이나 코드 리뷰어에게 공유해야 할 내용
- ViewModel은 제외하고, UI에서 호출하여 테스트 완료했습니다.

## 검증 코드
```kotlin
viewLifecycleOwner.lifecycleScope.launch {
            val repository = SearchLocationRepositoryImpl(RetrofitClient.searchAddress)

            runCatching {
                val data = repository.convertLocation(
                    query = "부송동 100"
                )

                Log.d("주소 검색 Success", data.toString())
            }.onFailure {
                Log.d("주소 검색 Error", it.toString())
            }
        }
```

2024-05-31 08:13 UTC, DoTheBestMayB requested changes
네이밍 관련 코멘트 남겼습니다!
FireStore를 위한 Service는 나중에 만드는 걸까요?

2024-05-31 08:13 UTC, DoTheBestMayB commented on data/src/main/java/com/bestapp/rice/data/model/remote/kakaomap/Meta.kt
> +    @Json(name = "total_count") val total_count: Int
변수 이름을 camelCase로 수정해야 할 것 같아요.

2024-05-31 08:13 UTC, DoTheBestMayB commented on data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
> +    // TODO: 카카오 Notification API 호출에 필요한 Repository로 변경해야함
Repository -> Service로 수정해야 할 것 같아요.

2024-05-31 08:13 UTC, DoTheBestMayB commented on data/src/main/java/com/bestapp/rice/data/network/RetrofitClient.kt
> +    val searchAddress: SearchLocationService =
변수 이름을 xxxService로 변경하면 더 명확해질 것 같아요.

2024-05-31 08:13 UTC, DoTheBestMayB commented on data/src/main/java/com/bestapp/rice/data/repository/SearchLocationRepository.kt
> +        @IntRange(from = 1, to = 30) size: Int = 10,
애노테이션 활용 좋습니다👍

2024-05-31 11:22 UTC, rlaxodud214 commented
수정했습니다.

2024-05-31 11:26 UTC, DoTheBestMayB approved these changes

2024-05-31 11:28 UTC, DoTheBestMayB approved these changes

2024-05-31 12:49 UTC, kory0115 approved these changes

2024-05-31 13:21 UTC, rlaxodud214 commented
FireStore를 위한 Service는 나중에 만드는 걸까요? 
주말에 figma 디자인 끝내고 작업해둘게요!!

2024-05-31 13:21 UTC, rlaxodud214 commented
> 네이밍 관련 코멘트 남겼습니다! FireStore를 위한 Service는 나중에 만드는 걸까요?

주말에 figma 디자인 끝내고 작업해둘게요!!

2024-05-31 20:12 UTC, yoonchanchoi approved these changes
구현하시느라 고생하셨습니다.^^

2024-05-31 20:12 UTC, yoonchanchoi commented on data/build.gradle.kts
> +val properties = Properties()
gradleLocalProperties를 사용하는 건 어떨까용?
LocalProperties는 Groovy에서 사용하기 때문에 많이 옛날 코드가 되버렸습니다.ㅠㅠ
gradleLocalProperties를 추천합니다. 튜터님도 이걸 추천하시더라고용 아마도 
kotlin DSL로 넘어오면서 조금 최신에 맞추자는 것 같습니다. 

취향입니다.ㅎㅎ

링크 첨부입니다.
https://velog.io/@yuuuzzzin/Android-local.properties%EB%A5%BC-%ED%86%B5%ED%95%B4-API-key-%EC%95%88%EC%A0%84%ED%95%98%EA%B2%8C-%EB%B3%B4%EA%B4%80%ED%95%98%EA%B8%B0

2024-06-02 08:46 UTC, rlaxodud214 commented on data/build.gradle.kts
> +val properties = Properties()
그렇군요?! 수정했습니다!!

2024-06-02 08:46 UTC, merged